In [ ]:
#tsp on a example distance matrix
import numpy as np
import itertools


def traveling_salesman(distance_matrix):
    n = len(distance_matrix)
    all_cities = range(n)
    min_distance = float("inf")
    best_path = None
    for path in itertools.permutations(all_cities):
        path = list(path)
        path_distance = 0
        for i in range(n - 1):
            path_distance += distance_matrix[path[i]][path[i + 1]]
        path_distance += distance_matrix[path[n - 1]][path[0]]
        if path_distance < min_distance:
            min_distance = path_distance
            best_path = path
    return best_path, min_distance

distance_matrix = np.array([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]])
best_path, min_distance = traveling_salesman(distance_matrix)
print(f"The shortest path is: {best_path}")
print(f"The minimum distance is: {min_distance}")


The shortest path is: [0, 2, 1, 3]
The minimum distance is: 23.599999999999998


In [ ]:
#find distance
import requests

def get_distance_and_time(origins, destinations, api_key):
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?"
    url += "origins=" + "|".join(origins) + "&destinations=" + "|".join(destinations) + "&key=" + api_key
    print(url)
    response = requests.get(url)
    data = response.json()
    
    distances = [row['elements'][0]['distance']['text'] for row in data['rows']]
    durations = [row['elements'][0]['duration']['text'] for row in data['rows']]
    
    return distances, durations

api_key = "AIzaSyBN-6JIDSQK8W9B6Y67BjF0B8ru8NKCVwM"
origins = ["Food point, vile parle east, mumbai"]
destinations = ["Kalpataru Yashodhan, Vile Parle West, Mumbai"]
# origins = ["Food point, vile parle east, mumbai","Maheshwar Mansion, Vile Parle West"]
# destinations = ["Kalpataru Yashodhan, Vile Parle West, Mumbai","Hubtown solaris, andheri east"]

distances, durations = get_distance_and_time(origins, destinations, api_key)
print(distances)

for i in range(len(origins)):
    print("From:", origins[i], "To:", destinations[i])
    print("Distance:", distances[i])
    print("Duration:", durations[i])
    print("\n")

https://maps.googleapis.com/maps/api/distancematrix/json?origins=Food point, vile parle east, mumbai&destinations=Kalpataru Yashodhan, Vile Parle West, Mumbai&key=AIzaSyBN-6JIDSQK8W9B6Y67BjF0B8ru8NKCVwM
['2.3 km']
From: Food point, vile parle east, mumbai To: Kalpataru Yashodhan, Vile Parle West, Mumbai
Distance: 2.3 km
Duration: 11 mins




In [ ]:
#final code for distance matrix
import requests

def get_distance_and_time(origins, destinations, api_key):
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?"
    url += "origins=" + origins + "&destinations=" + destinations + "&key=" + api_key
    #print(url)

    response = requests.get(url)
    data = response.json()
    
    distances = [row['elements'][0]['distance']['text'] for row in data['rows']]
    durations = [row['elements'][0]['duration']['text'] for row in data['rows']]
    
    return distances, durations

import numpy as np
api_key = "AIzaSyBN-6JIDSQK8W9B6Y67BjF0B8ru8NKCVwM"
# Example list of vectors
vectors = ["Food point, vile parle east, mumbai","Maheshwar Mansion, Vile Parle West","Kalpataru Yashodhan, Vile Parle West, Mumbai","Hubtown solaris, andheri east"]

# Initialize a square matrix of zeros with dimensions equal to the length of the vector list
n = len(vectors)
#dist_matrix = np.zeros((n, n))
dist_matrix = [['' for j in range(n)] for i in range(n)]
time_matrix = [['' for j in range(n)] for i in range(n)]

# Fill the matrix with the Euclidean distance between each pair of vectors
for i in range(n):
    for j in range(n):
      if j<i:
        print(vectors[i]," ",vectors[j])
        distances, durations = get_distance_and_time(vectors[i], vectors[j], api_key)
        print(distances[0]," ",durations[0])      
        dist_matrix[i][j] = distances[0]
        time_matrix[i][j] = durations[0]

print(dist_matrix)
print(time_matrix)

Maheshwar Mansion, Vile Parle West   Food point, vile parle east, mumbai
1.6 km   7 mins
Kalpataru Yashodhan, Vile Parle West, Mumbai   Food point, vile parle east, mumbai
2.2 km   9 mins
Kalpataru Yashodhan, Vile Parle West, Mumbai   Maheshwar Mansion, Vile Parle West
1.1 km   5 mins
Hubtown solaris, andheri east   Food point, vile parle east, mumbai
1.4 km   6 mins
Hubtown solaris, andheri east   Maheshwar Mansion, Vile Parle West
2.4 km   9 mins
Hubtown solaris, andheri east   Kalpataru Yashodhan, Vile Parle West, Mumbai
2.9 km   13 mins
[['', '', '', ''], ['1.6 km', '', '', ''], ['2.2 km', '1.1 km', '', ''], ['1.4 km', '2.4 km', '2.9 km', '']]
[['', '', '', ''], ['7 mins', '', '', ''], ['9 mins', '5 mins', '', ''], ['6 mins', '9 mins', '13 mins', '']]


In [ ]:
import re

# Example string
s = ['1.5 km']

# Remove the text and extract the number
num = re.findall(r'\d+\.\d+', s[0])[0]

print(num)  # Output: 19.99


1.5


In [ ]:
#jk code  for distance matrix with type float
import requests
import re 

def get_distance_and_time(origins, destinations, api_key):
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?"
    url += "origins=" + origins + "&destinations=" + destinations + "&key=" + api_key
    #print(url)

    response = requests.get(url)
    data = response.json()
    
    distances = [row['elements'][0]['distance']['text'] for row in data['rows']]
    durations = [row['elements'][0]['duration']['text'] for row in data['rows']]
    
    return distances, durations

import numpy as np
api_key = "AIzaSyBN-6JIDSQK8W9B6Y67BjF0B8ru8NKCVwM"
# Example list of vectors
vectors = ["Food point, vile parle east, mumbai","Taj Lands End, Bandstand","Kalpataru Yashodhan, Vile Parle West, Mumbai","Prem Griha, Santacruz West"]

# Initialize a square matrix of zeros with dimensions equal to the length of the vector list
n = len(vectors)
dist_matrix = np.zeros((n, n))
time_matrix = np.zeros((n, n))

# dist_matrix = [['' for j in range(n)] for i in range(n)]
# time_matrix = [['' for j in range(n)] for i in range(n)]

# Fill the matrix with the Euclidean distance between each pair of vectors
for i in range(n):
    for j in range(n):
      if j<i:
        print(vectors[i]," ",vectors[j])
        distances, durations = get_distance_and_time(vectors[i], vectors[j], api_key)
        dist = float(re.findall(r'\d+\.\d+', distances[0])[0])
        #time = float(re.findall(r'\d+\.\d+', durations[0])[0])
        print(dist," ",durations[0])  
        dist_matrix[i][j] = dist
        #time_matrix[i][j] = time
        

print(dist_matrix)
#print(time_matrix)

dist_matrix += np.tril(dist_matrix, -1).T
print(dist_matrix)

Taj Lands End, Bandstand   Food point, vile parle east, mumbai
12.5   25 mins
Kalpataru Yashodhan, Vile Parle West, Mumbai   Food point, vile parle east, mumbai
2.2   9 mins
Kalpataru Yashodhan, Vile Parle West, Mumbai   Taj Lands End, Bandstand
9.2   37 mins
Prem Griha, Santacruz West   Food point, vile parle east, mumbai
5.7   19 mins
Prem Griha, Santacruz West   Taj Lands End, Bandstand
5.4   22 mins
Prem Griha, Santacruz West   Kalpataru Yashodhan, Vile Parle West, Mumbai
4.7   19 mins
[[ 0.   0.   0.   0. ]
 [12.5  0.   0.   0. ]
 [ 2.2  9.2  0.   0. ]
 [ 5.7  5.4  4.7  0. ]]
[[ 0.  12.5  2.2  5.7]
 [12.5  0.   9.2  5.4]
 [ 2.2  9.2  0.   4.7]
 [ 5.7  5.4  4.7  0. ]]


In [ ]:
#tsp code on distance matrix
import numpy as np
import itertools

def traveling_salesman(distance_matrix):
    n = len(distance_matrix)
    all_cities = list(range(1, n))
    min_distance = float("inf")
    best_path = None
    for path in itertools.permutations(all_cities):
        path = [0] + list(path)
        path_distance = 0
        for i in range(n - 1):
            if path[i] < path[i + 1]:
                path_distance += distance_matrix[path[i]][path[i + 1]]
            else:
                path_distance += distance_matrix[path[i + 1]][path[i]]
        path_distance += distance_matrix[path[n - 1]][path[0]]
        if path_distance < min_distance:
            min_distance = path_distance
            best_path = path
    return best_path, min_distance

# Define a triangular distance matrix
# distance_matrix = np.array([[0, 0, 0, 0], [10, 0, 0, 0], [15, 35, 0, 0], [20, 25, 30, 0]])
# print(distance_matrix)

# Make the matrix symmetric by copying the lower triangular part to the upper triangular part
# dist_matrix += np.tril(dist_matrix, -1).T
# print(dist_matrix)

best_path, min_distance = traveling_salesman(dist_matrix)
print(f"The shortest path is: {best_path}")
print(f"The minimum distance is: {min_distance}")


The shortest path is: [0, 2, 1, 3]
The minimum distance is: 23.599999999999998
